language: python
sudo: false
python:
  - "2.7"
services:
  - couchdb
cache:
  directories:
    - eggs
env:
  - TZ=Europe/Kiev
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/15e2534ac51757c92e72
    on_success: always
    on_failure: always
    on_start: false
